### PR TITLE
Handles internal exception as a 500 response

### LINKED ISSUE #80: Handle thrown errors
I'd love it if errors my resolvers throw would get converted to rejected responses with a status code of 500. That way the app doesn't come crashing down if I hit something unexpected.

### PR DESCRIPTION
**Pull request by kettanaito**
> This change bumps the integrity checksum of the Service Worker. Users would have to update the Service Worker, following the instructions in the integrity failure error message.

## GitHub

- Fixes #80 

## Changes

- `handleRequestWith` now executes in a `try`/`catch` block
- Any exceptions originating from a request handler are signaled to the Service Worker and it responds with a 500 response, including a suggestion error message to handle the exception, and the detailed original exception in the response's body

## TODO

- [x] Rewrite the successful mock signal from `channel.send(body)` to `channel.send({ type: '...', payload: body })` to be aligned with all the other signals

### CODE REVIEW

File: src/handleRequest.ts [hunk 1]
```diff
@@ -14,79 +14,97 @@ import {
...
+
+      channel.send({
+        type: 'MOCK_SUCCESS',
+        payload: responseWithHeaders,
+      })
+    } catch (error) {
+      channel.send({
+        type: 'INTERNAL_ERROR',
+        payload: {
+          status: 500,
```
Comment (kentcdodds) [inline src/handleRequest.ts:100]: Could this be: `error.status || 500`?

Comment (kettanaito) [reply src/handleRequest.ts:100]: Hm. Could you please give me an example of such error?

Please note that throwing in request handlers is not the recommended way of mocking server errors. I'd strongly recommend mocking server errors according to [this guide](https://redd.gitbook.io/msw/recipes/mocking-error-responses), which implies composing an error response via `res()`.
