### PR TITLE
fix: parse request body with letter case header

### LINKED ISSUE #171: Request JSON body is not parsed in Node
## Describe the bug
When mocking a request in NodeJS and performing a request with `Content-Type: application/json`, the `req.body` reference in a request handle is stringified body, instead of a parsed one (see #159).

## Environment

- `msw: 0.16.1`
- `nodejs: v10.18.1`
- `npm: 6.13.4`

## To Reproduce

```js
const server = setupServer(
  rest.post('https://test.msw.io', (req, res, ctx) => {
    return res(
      ctx.status(403),
      ctx.set('x-header', 'yes'),
      ctx.json(req.body as Record<string, any>),
    )
  }),
)

server.listen()

fetch('https://test.msw.io', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    payload: 'info',
  }),
})
```

## Expected behavior
Request's JSON body is always parsed to a JavaScript object, regardless if running in browser or node.

## Screenshots
```diff
+  Expected: {"payload": "info"}
-  Received: "{\"payload\":\"info\"}"
```

### PR DESCRIPTION
**Pull request by whyDontI**
Fixes the problem mentioned in this [comment](https://github.com/mswjs/msw/pull/172#discussion_r786449936)

The request body is not parsed if the `Content-type` header has the value with letter cases like `Application/JSON`.

# GitHub
Fixes #171 (Might need to reopen or create a new one)

### CODE REVIEW

File: src/utils/request/parseBody.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ export function parseBody(body?: MockedRequest['body'], headers?: Headers) {
     return body
   }
 
-  const contentType = headers?.get('content-type') || ''
+  const contentType = (headers?.get('content-type') || '').toLowerCase()
```
Comment (kettanaito) [inline src/utils/request/parseBody.ts]: That's a nice catch. What do you think if we utilize optional chaining here since we're already using it?

```suggestion
  const contentType = headers?.get('content-type')?.toLowerCase() || ''
```

Comment (whyDontI) [reply src/utils/request/parseBody.ts]: Sure 👍🏽

**Review by kettanaito — APPROVED** [review]
Thank you for fixing this, @whyDontI! Welcome to contributors 🎉
