### PR TITLE
fix: support async generators as response resolvers

### LINKED ISSUE #2109: "Cannot read properties of undefined (reading 'get')" when using generators/async generators as resolvers
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

20.11

### Reproduction repository

https://github.com/juliusmarminge/msw-async-generator

### Reproduction steps

`bun i && bun run test`

### Current behavior

CleanShot 2024-03-25 at 13 01 38@2x

### Expected behavior

According to the docs here: https://mswjs.io/docs/recipes/polling async generator should be supported

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #2109 
- Adds failing integration tests for using a generator (and async generator) function as response resolvers. 
- Supports async generators as response resolvers (generally, supports any iterators/async iterators!).
- Adds missing type tests for generators and async generators as response resolvers (needs #2107 to properly pass).

### CODE REVIEW

File: src/core/handlers/RequestHandler.ts [hunk 1]
```diff
@@ -256,6 +266,9 @@ export abstract class RequestHandler<
       return null
     }
 
+    // Preemptively mark the handler as used.
+    // Generators will undo this because only when the resolver reaches the
+    // "done" state of the generator that it considers the handler used.
     this.isUsed = true
```
Comment (kettanaito) [inline src/core/handlers/RequestHandler.ts:276]: It's important to mark the handler as used immediately, even if using generators then opts-out from this behavior. This is what we promise right now, so let's keep that promise.

File: src/core/handlers/RequestHandler.ts [hunk 2]
```diff
@@ -57,6 +56,11 @@ export type AsyncResponseResolverReturnType<
       MaybeAsyncResponseResolverReturnType<ResponseBodyType>,
       MaybeAsyncResponseResolverReturnType<ResponseBodyType>
     >
+  | AsyncGenerator<
```
Comment (kettanaito) [inline src/core/handlers/RequestHandler.ts]: Older versions of TypeScript (4.7 - 5.2) have trouble digesting this type:

```
 FAIL  resolver-generator.test-d.ts > supports async generator function as response resolver
TypeCheckError: Argument of type '() => AsyncGenerator<StrictResponse<JsonBodyType>, StrictResponse<JsonBodyType>, any>' is not assignable to parameter of type 'HttpResponseResolver<never, never, { value string; }>'.
  Type 'AsyncGenerator<StrictResponse<JsonBodyType>, StrictResponse<JsonBodyType>, any>' is not assignable to type 'AsyncResponseResolverReturnType<{ value string; }>'.
    Type 'AsyncGenerator<StrictResponse<JsonBodyType>, StrictResponse<JsonBodyType>, any>' is not assignable to type 'AsyncGenerator<ResponseResolverReturnType<{ value string; }>, ResponseResolverReturnType<{ value string; }>, ResponseResolverReturnType<{ value string; }>>'.
      The types returned by 'next(...)' are incompatible between these types.
        Type 'Promise<IteratorResult<StrictResponse<JsonBodyType>, StrictResponse<JsonBodyType>>>' is not assignable to type 'Promise<IteratorResult<ResponseResolverReturnType<{ value string; }>, ResponseResolverReturnType<{ value string; }>>>'.
          Type 'IteratorResult<StrictResponse<JsonBodyType>, StrictResponse<JsonBodyType>>' is not assignable to type 'IteratorResult<ResponseResolverReturnType<{ value string; }>, ResponseResolverReturnType<{ value string; }>>'.
            Type 'IteratorYieldResult<StrictResponse<JsonBodyType>>' is not assignable to type 'IteratorResult<ResponseResolverReturnType<{ value string; }>, ResponseResolverReturnType<{ value string; }>>'.
              Type 'IteratorYieldResult<StrictResponse<JsonBodyType>>' is not assignable to type 'IteratorYieldResult<ResponseResolverReturnType<{ value string; }>>'.
                Type 'StrictResponse<JsonBodyType>' is not assignable to type 'ResponseResolverReturnType<{ value string; }>'.
```

## Reproduction steps

- TypeScript 4.7
- `pnpm test:ts`

Comment (kettanaito) [reply src/core/handlers/RequestHandler.ts]: Hi, @Andarist! Sorry for troubling you once again. If you have a minute, could you please lend me a hand with this type issue?

Comment (Andarist) [reply src/core/handlers/RequestHandler.ts]: I would need to see a slimmed-down repro. The one that I tried put together in a rush errors in the current TS version too: [TS playground](https://www.typescriptlang.org/play?target=99&lib=lib.esnext.d.ts&ts=5.3.3#code/PTAEAEBsEsCMC5QFMDOA7JAPALgWAFDRrZIBOAZgIYDGSoASqgA4D2aKdA3gL4EHYBPJnQCylAbCQAFUiwC20DgB4AKgD5QAXlArQAH1Az5ipKrUBuPvgAmSapEqk61NimyhYLawJVCkiAFc0aABHALoUATlPSEt8AiISCho6AGVsUmhqbEYUVnZTACEvHz8NLBI0axQGZlcuAlBQJ0prNkgBUABtT29fYQBdRGK+vzjeePxBYVq8+tyWSAA3MkZsANI0ftNc-I4R0uENTUb9UAAKLt36g+2B5BwkKpquoNtyIiRrAdOmpoB+WZ7JC-P6IdKZbLXApKaH7ErbNQASlOBjeSA+GGsqNASxY0GscX4flAYgkSAAgpE0NQ4UgFstVkh1pttrC6gVbmUtKTxJIjAplKc6QyVqQ1hstn52XNOQiygQLFZpnQqQIaSLUIsxRLWdK6VyjjyyfzZILTDjNShtUyWVLhDLgYakGocQBxJ5kSjYFikJSgpomynU2kcjii22StkG+VHAA0Ad55LVGrD9K1jPFzKj+rTzrUCfwfz+QZTodl4YzOuzeodMdGR1BrvwSsmKqB8yrZBlNtIAFEcKRKABJNDkFhx2phVDYZ2T+uHF0886nIjjxAR-uDkdjicEJFaDRlq293X2nZ52MuuLtgAS2GwTBPmaUUkclDkKHnSGnbjnHblBslxOIsAMra0XzfIdP2-X9Zyvb8KyQfMiXwcggmyaA2FAEg3BXUCnAgsVEHvR9nzFJQMDFScqLISdOFxShIHCRA3EyNAAHNQG4At91AHhlRnc5KBDUB0JpbAsLQAAqC4Dx4JE4iwVhSHcHg4iAA)

Comment (kettanaito) [reply src/core/handlers/RequestHandler.ts]: Thanks for giving it a try, @Andarist. Here's a minimal repro:

```sh
pnpm install
pnpm build
pnpm test:ts test/typings/resolver-generator.test-d.ts
```

Comment (Andarist) [reply src/core/handlers/RequestHandler.ts]: That is not exactly minimal ;p it still depends on everything in the MSW's codebase. I could really use a self-contained TS playground here.

Comment (jakebailey) [reply src/core/handlers/RequestHandler.ts]: I stumbled on this and tried to bisect (via https://www.npmjs.com/package/every-ts) when this would have changed between 5.2 and 5.3.

What I discovered is that it's the literal version bump from 5.2 to 5.3; something in this package or its dependencies must be doing some typesVersions shenanigans that is causing this error.

Comment (jakebailey) [reply src/core/handlers/RequestHandler.ts]: Hmmm, no, I just flipped back and forth between the commits and now the 5.3 version change is failing. This makes no sense.

Comment (jakebailey) [reply src/core/handlers/RequestHandler.ts]: Skipping using `test:ts` and just doing regular compilation shows that https://github.com/microsoft/TypeScript/pull/51196 made this code legal. I'm not sure that there's really anything that can be done if you're hitting a limitation that was fixed.

Comment (kettanaito) [reply src/core/handlers/RequestHandler.ts]: Thank you so much for investigating this, @jakebailey! 

I'm glad to hear the team has fixed that (what a specific issue though!). Sadly, I don't expect they will backport the fix to all downstream versions that are not EOL. As CI reports, TS v5.3+ is fine with this change, but there's a huge chunk of versions MSW still supports before that. 

But one thing I'd like to clarify from your findings: is that a fundamentally TypeScript issue? Can we overcome it in any way on our end? Because if not, then this issue, transitively, also becomes a TS-caused issue, and we can only fix it once v5.3 becomes the minimal supported one.

Comment (jakebailey) [reply src/core/handlers/RequestHandler.ts]: We in general don't backport anything except critical regression fixes to the recent version (i.e. we're patching 5.5 right now).

I'm honestly not an expert in these types or their intracacies, so I can't really offer any other solution up for this... At best I could play around with the PR to attempt to make something pass, though I think anyone could probably do just as good as me in that area 😅

Comment (kettanaito) [reply src/core/handlers/RequestHandler.ts]: If you have the time, I'd be grateful! I gave it my best but my knowledge here ran short.

Comment (mattcosta7) [reply src/core/handlers/RequestHandler.ts]: > We in general don't backport anything except critical regression fixes to the recent version (i.e. we're patching 5.5 right now).
> 
> I'm honestly not an expert in these types or their intracacies, so I can't really offer any other solution up for this... At best I could play around with the PR to attempt to make something pass, though I think anyone could probably do just as good as me in that area 😅

I was looking into this a bit too - happy to have assistance if you have ideas - it's been an interesting one, and also not super familiar with these types

Comment (jakebailey) [reply src/core/handlers/RequestHandler.ts]: I got some time to take a look and believe I have a solution which actually improves things further.

Firstly, the code actually only depends on the existence of `Symbol.iterator` (or in this PR, `Symbol.asyncIterator`). This means that it's not actually working with generators at all, it's working with `Iterable`/`AsyncIterable` (and in fact shows that `isIterable` is incorrectly defined).

By switching the types over to use types defined with _just_ those two props, inference works again.

Fixing the implementation to reflect those types takes a little bit more code, but the upshot is that the final result allows users to pass in any `Iterable`/`AsyncIterable` they want, not just generators. I think this would actually allow people to pass in lists/sets of responses if they wanted, though I don't know if that's desirable or not.

How can I send this change to you? This is just a branch on this repo, so should I just PR it over? Here's a patch you could apply as well: https://gist.github.com/jakebailey/9702b2e0f16e2c9ce59799e40aefc7e7

Comment (kettanaito) [reply src/core/handlers/RequestHandler.ts]: @jakebailey, that is incredible! 😮 I would love to give this a try. 

Please, could you open a PR to _this feature branch_ (`fix/generator-resolver`)? Let me know if you need any help. 

What you are proposing sounds fantastic. I think that's the way to go. Need to see whether it complies with the other expectations toward the resolvers (especially the `isUsed` stuff).

Comment (jakebailey) [reply src/core/handlers/RequestHandler.ts]: Yes, I can do that.

Comment (jakebailey) [reply src/core/handlers/RequestHandler.ts]: FWIW I did compile and test locally, and it all seemed to work, though I did not acutally test the full range of TS versions (but I can't imagine it wouldn't work, maybe I'm jinxing myself)

Comment (kettanaito) [reply src/core/handlers/RequestHandler.ts]: Happy to give this a try once it's here 👀 Installing different `typescript` dependency versions triggers the `test:ts` into using that version for testing. The CI will also cover all the ranges for us. So excited we may actually ship this!

Comment (jakebailey) [reply src/core/handlers/RequestHandler.ts]: Sent https://github.com/mswjs/msw/pull/2213.

FWIW if you're looking for multi-version testing and aren't too tied to vitest, https://github.com/tstyche/tstyche is one option I've heard of which automatically runs multiple versions of TS without having to install them explicitly.

Comment (kettanaito) [reply src/core/handlers/RequestHandler.ts]: That's nice! Something to consider in the setup.

**Comment by kettanaito** [comment]
The fix from @jakebailey (#2213) seems to fix the compatibility with older TypeScript versions! 🎉 Super job here. Any objections to merge this?

**Comment by jakebailey** [comment]
This technically now enables passing in arrays, maps, etc; is that desirable? Should it be tested?

**Comment by kettanaito** [comment]
@jakebailey as the return value of the resolver? It would be nice to guard against that on runtime at least.

**Comment by jakebailey** [comment]
Actually, the old code may have already allowed that, at least for like .values()...

**Comment by jakebailey** [comment]
It's probably fine as is, I'm just paranoid given I know nothing about this codebase!

**Comment by kettanaito** [comment]
@jakebailey, well, now you know a little bit :) I'm infinitely grateful for your work on this. Looks like I know another TypeScript wizard now. 

I will give that false matching types scenario a try before releasing this.

**Comment by kettanaito** [comment]
Yeah, @jakebailey, you're right. As long as the return type satisfies the Iterator type, there's no type error:

```ts
http.get('/user/:a/:b/:b', ({ params }) => {
  return []
  // ^ This compiles OK while it must error. 
})
```

**Comment by jakebailey** [comment]
I guess the question is whether or not that's bad or not; I can just as easily pass in a generator which never yields today, right?

**Comment by kettanaito** [comment]
That's certainly agains the established contract. Response resolvers either return/yield a `Response` instance or nothing. Nothing is an accepted value. But anything save for a `Response` instance is not. We don't have runtime guards against that now because we rely on type-level validation to prevent developers from returning non-Response stuff from their resolvers.

**Comment by kettanaito** [comment]
This only seems to be a problem when returning an empty array `() => []`. Arrays are iterable, and they will even respect the resolver return type (response type) so that `() => [123]` errors, but an empty array is okay. Exploring if I can tweak the types so that an empty iterator is not allowed but that's equivalent of having a generator that doesn't yield value, which is still okay in MSW world. 

Huh.

**Comment by kettanaito** [comment]
Oddly enough, I'm beginning to like the array stuff. Since arrays are iterable, one can return an array of mocked responses at once (no need for a generator). If that happens, MSW will exhaust that array as it does a generator function, producing mocked responses in order, and stopping on the last response to then use it forever. I wouldn't document this behavior but I like it!

**Comment by kettanaito** [comment]
## Released: v2.3.3 🎉

This has been released in v2.3.3!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.3.3)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.3.3)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
