### PR TITLE
mockServiceWorker: Short-circuits the fetch event on bypass state

### LINKED ISSUE #412: Chrome Dev tools XHR
## Describe the bug
Not sure if it is even a msw problem, but maybe someone knows the answer. For some reason, when msw is enabled, I can not set up a filter to see only XHR requests in Chrome network tab. See how it looks like below (note, that static files are displayed even though the XHR filter is on.)

## Environment

- `msw: 0.21.2`
- `nodejs: 12.16.1`
- `npm: 6.14.8`
- `Chrome Version 85.0.4183.121 (Official Build) (64-bit)`

## To Reproduce
1. Set up msw for browser as described in official docs
2. Open Chrome Dev Tools
3. Turn on filter XHR
4. Reload the page. 
5. You will see all requests.

## Expected behavior
Only XHR requests are displayed

## Screenshots
Screenshot 2020-10-02 at 15 33 02

### PR DESCRIPTION
**Pull request by kettanaito**
> This requires to update the worker script.

## GitHub

- Closes #412 

## Changes

~~Instead of requesting a bypasses request once more, short circuit the `fetch` handler in the worker for it to bypass that request. This will get rid of requests duplications and won't list static assets in the XHR tab of a browser's DevTools.~~

- Short circuits on the navigation requests outside of the `respondWith` scope.
- Short circuits on the `!clients[clientId]` requests outside of the `respondWith` scope.
- Fixes an issue that some requests are still marked as "from ServiceWorker" after the worker has been unregistered.

### CODE REVIEW

**Comment by kettanaito** [comment]
We may also want to short circuit on `MOCK_NOT_FOUND` case, where a request was captured, but there was no respective request handler, so it got performed as-is.

**Comment by marcosvega91** [comment]
I didn't know that trick, fine !!

File: src/mockServiceWorker.js [hunk 1]
```diff
@@ -97,7 +97,7 @@ self.addEventListener('fetch', async function (event) {
         // Bypass mocking for navigation requests
         request.mode === 'navigate'
       ) {
-        return resolve(getOriginalResponse())
+        return
```
Comment (malykhinvi) [inline src/mockServiceWorker.js]: Is it ok that the promise is never resolved in that case? Why we can not do an early return before the `event.respondWith`?

Comment (kettanaito) [reply src/mockServiceWorker.js]: Early return before `event.respondWith` throws an exception that request cannot be handled because the event is closed. 

Good point about pending Promise. I'm not sure if it's an issue, though. We shouldn't resolve it, that will cause a fake response without any data.

Comment (marcosvega91) [reply src/mockServiceWorker.js]: I'm not sure that it will work. Intercepting the `fetch` I think that we should provide a way to resolve the request, fetching from original one or from cache, or mocking as our case.

Comment (kettanaito) [reply src/mockServiceWorker.js]: The fact that it performs the request may imply that it actually works as intended. Had the promise given to `respondWith` been pending forever, we'd receive a forever pending request in the network.

That being said, there are some failing tests on CI with a navigation timeout. This may be caused by multiple factors, including forever pending requests. I haven't encountered those while manually testing.

Comment (kettanaito) [reply src/mockServiceWorker.js]: You are right: not resolving a Promise here causes an infinitely pending request. I haven't spotted this due to some race conditions between the worker registration and the request dispatch. Now I can see that.

File: src/mockServiceWorker.js [hunk 2]
```diff
@@ -74,11 +74,22 @@ self.addEventListener('message', async function (event) {
   }
 })
 
-self.addEventListener('fetch', async function (event) {
```
Comment (kettanaito) [inline src/mockServiceWorker.js:77]: Fetch event handler function cannot be async per specification. Marking it as `async` here is misleading: you cannot use `await` within its top scope, it will cause an invalid state exception (cannot handle fetch event that's already handled).

File: src/mockServiceWorker.js [hunk 3]
```diff
@@ -74,11 +74,22 @@ self.addEventListener('message', async function (event) {
...
+self.addEventListener('fetch', function (event) {
   const { clientId, request } = event
   const requestClone = request.clone()
   const getOriginalResponse = () => fetch(requestClone)
 
+  // Bypass navigation requests.
+  if (request.mode === 'navigate') {
```
Comment (kettanaito) [inline src/mockServiceWorker.js:83]: Navigation requests can be bypassed early, so I'm moving them outside of the `event.respondWith` promise. This way navigation requests are performed as-is, not within the worker's scope.

File: src/mockServiceWorker.js [hunk 4]
```diff
@@ -74,11 +74,22 @@ self.addEventListener('message', async function (event) {
...
+    return
+  }
+
+  // Bypass mocking if the current client isn't present in the internal clients map
+  // (i.e. has the mocking disabled).
+  if (!clients[clientId]) {
+    return
```
Comment (kettanaito) [inline src/mockServiceWorker.js:90]: When the client hasn't yet sent the `MOCK_ACTIVATE` event bypass early as well. Requests made between the worker registration and worker activation are performed as-is. This includes static assets as well, they won't be marked as XHR in this time window.

Note that the time window is subjected to a race condition, as worker activation and registration are both asynchronous actions and may happen with a different time distance.

File: test/msw-api/unregister.test.ts [hunk 5]
```diff
@@ -35,10 +35,7 @@ test('unregisters itself when not prompted to be activated again', async () => {
   })
   const secondBody = await secondResponse.json()
 
-  // Although the Service Worker unregisters itself upon refreshing the page,
-  // it still remains "active and running" with the "deleted" status.
-  // This results into requests go through the Service Worker until the next reload.
-  expect(secondResponse.fromServiceWorker()).toBe(true)
+  expect(secondResponse.fromServiceWorker()).toBe(false)
```
Comment (kettanaito) [inline test/msw-api/unregister.test.ts:38]: Moving the navigation request bypassing out of the `respondWith` scope now fixes the issue that marked the first request as served from the worker, even after the worker has been unregistered. This test is now actually correct.

File: src/mockServiceWorker.js (hunk 3 above)
Comment (marcosvega91) [reply src/mockServiceWorker.js:83]: this is a great catch !

**Review by marcosvega91 — DISMISSED** [review]
everything ok !! I didn't thought that solution, Great !
