### PR TITLE
fix: null-body responses enforced in createResponseListener instead o…

### LINKED ISSUE #1893: Faulty 304 handling results in `Failed to construct 'Response'` error
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

- Chrome (119.0.6045.123)
- Firefox (120.0)

### Reproduction repository

https://github.com/halfbakedsneed/msw-bad-304-handling

### Reproduction steps

```
pnpm install
pnpm start
```

Browse to http://localhost:3000 and hit "Click Me"

### Current behavior

For "bypassed" requests, responses with a `304` status code will result in the following being thrown:

```
Failed to construct 'Response': Response with null body status cannot have body
TypeError: Failed to construct 'Response': Response with null body status cannot have body
    at http://localhost:3000/static/js/bundle.js:48332:69
    at ServiceWorkerContainer.<anonymous> (http://localhost:3000/static/js/bundle.js:48595:15)
```

### Expected behavior

The service worker script correctly treats responses with a `204` status code [differently](https://github.com/mswjs/msw/blob/main/src/mockServiceWorker.js#L124-L128) when handling responses. The same behaviour should be exhibited when handling `304` responses, such that an error is not thrown.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304

>The response must not contain a body...

### PR DESCRIPTION
**Pull request by mattcosta7**
closes https://github.com/mswjs/msw/pull/1894
fixes #1893 

This should fix passthrough errors specifically, where the body was a stream and the status code cannot support a body.

### CODE REVIEW

File: src/mockServiceWorker.js [hunk 1]
```diff
@@ -121,11 +121,6 @@ async function handleRequest(event, requestId) {
   if (client && activeClientIds.has(client.id)) {
     ;(async function () {
       const responseClone = response.clone()
-      // When performing original requests, response body will
-      // always be a ReadableStream, even for 204 responses.
-      // But when creating a new Response instance on the client,
-      // the body for a 204 response must be null.
-      const responseBody = response.status === 204 ? null : responseClone.body
```
Comment (mattcosta7) [inline src/mockServiceWorker.js:128]: I moved this transform into the `createResponseListener` method, which is where we attempted to construct the Response with a body incorrectly

File: src/browser/setupWorker/start/createResponseListener.ts [hunk 2]
```diff
@@ -25,10 +25,14 @@ export function createResponseListener(context: SetupWorkerInternalContext) {
...
-        ? Response.error()
-        : new Response(responseJson.body, responseJson)
+    let response: Response
+    if (responseJson.status === 0) {
+      response = Response.error()
+    } else if (isResponseWithoutBody(responseJson.status)) {
+      response = new Response(null, responseJson)
+    } else {
+      response = new Response(responseJson.body, responseJson)
+    }
```
Comment (mattcosta7) [inline src/browser/setupWorker/start/createResponseListener.ts]: Handling this here instead of in the worker. this gives us a more integrated place to handle this, and makes it easy to reuse the helper from interceptors

Comment (mattcosta7) [reply src/browser/setupWorker/start/createResponseListener.ts]: could extract to a small method, not sure it's worth jumping out of line here though

File: test/browser/msw-api/regression/null-body.test.ts [hunk 3]
```diff
@@ -1,20 +1,22 @@
...
-  })
+    const errors: Array<Error> = []
+    page.on('pageerror', (pageError) => {
+      errors.push(pageError)
+    })
 
-  await fetch('/api/books')
-  await sleep(500)
+    await fetch(`/api/${code}`)
+    await sleep(500)
```
Comment (kettanaito) [inline test/browser/msw-api/regression/null-body.test.ts]: Why sleep? I think this is a good opportunity to remove it. I don't believe it's needed. There are no delays in the mocked responses, and if we want to await some side effect, we need to write a proper promise for that.

Comment (mattcosta7) [reply test/browser/msw-api/regression/null-body.test.ts]: just bad copy/paste - will drop that

File: test/node/msw-api/req/passthrough.node.test.ts [hunk 4]
```diff
@@ -9,6 +9,15 @@ const httpServer = new HttpServer((app) => {
   app.post<never, ResponseBody>('/user', (req, res) => {
     res.json({ name: 'John' })
   })
+  app.post('/code/204', (req, res) => {
```
Comment (kettanaito) [inline test/node/msw-api/req/passthrough.node.test.ts]: Nitpick: why not

```js
app.post('/code/:code', (req, res) => {
  res.status(req.params.code).end()
})
```

File: test/node/msw-api/req/passthrough.node.test.ts [hunk 5]
```diff
@@ -88,3 +97,35 @@ it('performs a request as-is if nothing was returned from the resolver', async (
     name: 'John',
   })
 })
+
+it.each([{ code: 204 }, { code: 205 }, { code: 304 }])(
```
Comment (kettanaito) [inline test/node/msw-api/req/passthrough.node.test.ts]: It'd be simpler to keep the array of status codes, the same you do in the other tests.

File: test/node/msw-api/req/passthrough.node.test.ts [hunk 6]
```diff
@@ -88,3 +97,35 @@ it('performs a request as-is if nothing was returned from the resolver', async (
...
+  'performs a $code request as-is if nothing was returned from the resolver',
```
Comment (kettanaito) [inline test/node/msw-api/req/passthrough.node.test.ts]: `$code` looks like a non-resolved template string value, does it not?

**Comment by kettanaito** [comment]
Does this change negate #1894? If so, we can mark it as "Closes #1894".

File: src/browser/setupWorker/start/createResponseListener.ts [hunk 7]
```diff
@@ -3,7 +3,7 @@ import {
   SetupWorkerInternalContext,
 } from '../glossary'
 import { ServiceWorkerMessage } from './utils/createMessageChannel'
-
+import { isResponseWithoutBody } from '@mswjs/interceptors'
```
Comment (kettanaito) [inline src/browser/setupWorker/start/createResponseListener.ts:6]: Nitpick: a new line after the import would be nice. Are by any chance not running Prettier?

File: src/browser/setupWorker/start/createResponseListener.ts [hunk 8]
```diff
@@ -25,10 +25,14 @@ export function createResponseListener(context: SetupWorkerInternalContext) {
       return
     }
 
-    const response =
-      responseJson.status === 0
-        ? Response.error()
-        : new Response(responseJson.body, responseJson)
+    let response: Response
```
Comment (kettanaito) [inline src/browser/setupWorker/start/createResponseListener.ts]: Would this be too confusing, in your opinion? 

```js
const response = responseJson.status === 0
  ? Response.error()
  : new Response(isResponseWithoutBody(responseJson.status) ? null : responseJson.body, responseJson)
```

Comment (kettanaito) [reply src/browser/setupWorker/start/createResponseListener.ts]: But yes, overall, I prefer this being a standalone method that we can also unit test to perfection. That way the usage is clear and the implementation can use early returns to stay clear also.

Comment (mattcosta7) [reply src/browser/setupWorker/start/createResponseListener.ts]: I think this style inline is probably the easiest to read, but not necessarily a big deal either way. 

Since we don't do this anywhere else, extracting it seems heavy, and more annoying to skim through, but no strong feeling

File: test/node/msw-api/req/passthrough.node.test.ts (hunk 6 above)
Comment (mattcosta7) [reply test/node/msw-api/req/passthrough.node.test.ts]: `.each` extracts that `$code` and inlines the value from the object. 

Playwright doesn't support it but vitest does.  we could do either way, but I was just doing this style here because the runner supports it.

File: test/node/msw-api/req/passthrough.node.test.ts (hunk 4 above)
Comment (mattcosta7) [reply test/node/msw-api/req/passthrough.node.test.ts]: no reason, really.  I went back and forth on this actually, and settled on the explicit handlers, since it's a bit easier to parse quickly that we're only defining a couple codes that we care about vs arbitrary ones (especially if we typod a non-numeric code)

File: src/browser/setupWorker/start/createResponseListener.ts (hunk 7 above)
Comment (mattcosta7) [reply src/browser/setupWorker/start/createResponseListener.ts:6]: I usually have it running, maybe it just lagged in vscode?

**Review by kettanaito — APPROVED** [review]
🚀

**Comment by kettanaito** [comment]
## Released: v2.0.10 🎉

This has been released in v2.0.10!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.0.10)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.0.10)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
