### PR TITLE
Fix IE11 string split issue with error stack

### LINKED ISSUE #646: MSW throws a string parse error when an undefined or null stack trace is encountered
## Describe the bug
In IE11 when a new Error is thrown with an `undefined` or a `null` `stack`, a parse error is thrown.

```
Queuing uncaught exception from window.onerror Unable to get property 'split' of undefined or null reference  349 3 TypeError: Unable to get property 'split' of undefined or null reference
SCRIPT5007: Unable to get property 'split' of undefined or null reference
getCallFrame-deps.js (349,3)
```

## Environment

- `msw: 0.26.2`
- `nodejs: 14.15.4`
- `npm: 6.14.10`

> Please also provide your browser version.

image
- `IE 11.15.16299.0`

## To Reproduce
1. Go to the console in IE11
2. Throw a new error and output the stack
3. Inline the MSW `getCallFrame()` `frame` logic
4. See the parse `TypeError`

image

## Expected behavior
MSW should gracefully handle an `undefined` or `null` stack by converting to an empty string.

### PR DESCRIPTION
**Pull request by seriouslysean**
Solves #646.

### CODE REVIEW

File: src/utils/internal/getCallFrame.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@
  * Return the stack trace frame of a function's invocation.
  */
 export function getCallFrame() {
-  const frames: string[] = (new Error().stack as string).split('\n')
+  const frames: string[] = ((new Error().stack || '') as string).split('\n')
```
Comment (seriouslysean) [inline src/utils/internal/getCallFrame.ts]: Full disclosure, I haven't done much TS at all-- mostly only reading so if this needs to change or there is a better way to write it I'm all ears.

Comment (msutkowski) [reply src/utils/internal/getCallFrame.ts]: The only other option would be `??` it, but it doesn't really matter here and the `||` makes sense. I think for future readability, we should add a comment above this explaining why this is here (ex: < IE11 returns `undefined` instead of a string).

**Review by msutkowski — COMMENTED** [review]
Wild catch! IE is the gift that keeps on giving :)

File: src/utils/internal/getCallFrame.ts (hunk 1 above)
Comment (seriouslysean) [reply src/utils/internal/getCallFrame.ts]: Thanks @msutkowski, added in 1b3873afba671d3fe707f6e019264a1c6fa931f8.

File: src/utils/internal/getCallFrame.test.ts [hunk 2]
```diff
@@ -168,3 +168,15 @@ test('Safari on macOS error stack', () => {
     './test/msw-api/setup-worker/printHandlers.mocks.ts@http://localhost:56460/main.js:1376:5',
   )
 })
+
+test('IE11 undefined or null error stack', () => {
```
Comment (kettanaito) [inline src/utils/internal/getCallFrame.test.ts]: Could you please rename this test title to something like

```suggestion
test('handles the undefined stack trace', () => {
```

File: src/utils/internal/getCallFrame.test.ts [hunk 3]
```diff
@@ -168,3 +168,15 @@ test('Safari on macOS error stack', () => {
...
+  // version 1
+  mockStack.mockImplementationOnce(() => undefined)
+
+  expect(() => getCallFrame()).not.toThrow(TypeError)
+
+  // version 2
```
Comment (kettanaito) [inline src/utils/internal/getCallFrame.test.ts]: You can drop these comments, I think you're doing a great job with the test so the things are self-explanatory.

File: src/utils/internal/getCallFrame.ts (hunk 1 above)
Comment (kettanaito) [reply src/utils/internal/getCallFrame.ts]: We should be careful about `??`, since that wouldn't handle `false`, which is still an unexpected value that mustn't be treated as an error's stack trace. I think `||` is the way to go here.

File: src/utils/internal/getCallFrame.ts [hunk 4]
```diff
@@ -2,7 +2,8 @@
  * Return the stack trace frame of a function's invocation.
  */
 export function getCallFrame() {
-  const frames: string[] = (new Error().stack as string).split('\n')
+  // In <IE11, new Error may return an undefined stack
+  const frames: string[] = ((new Error().stack || '') as string).split('\n')
```
Comment (kettanaito) [inline src/utils/internal/getCallFrame.ts]: This line is getting quite complex, what do you think if we move it into its own variable?

```ts
const stack = (new Error().stack || '') as string
const frames: string[] = stack.split('\n')
```

It's subjective, but I find it to read much better.

**Review by kettanaito — CHANGES_REQUESTED** [review]
Hey, @seriouslysean! Thank you so much for working on this improvement. I've left only a few nitpick comments to push this pull request from good to awesome. Looking forward to seeing this merged.

File: src/utils/internal/getCallFrame.test.ts (hunk 3 above)
Comment (seriouslysean) [reply src/utils/internal/getCallFrame.test.ts]: Copy and paste was not my friend today, haha. 😬

File: src/utils/internal/getCallFrame.ts (hunk 4 above)
Comment (seriouslysean) [reply src/utils/internal/getCallFrame.ts]: I actually had it this way first, adjusted in 895af0f05cbd9f2667ed02dc4622e026bd15299f.

**Comment by seriouslysean** [comment]
Thanks @kettanaito, should be good to go now-- thanks for the quick feedback. I can tell that we're all SUPER passionate about IE11 support, haha. 😎

**Review by msutkowski — APPROVED** [review]
LGTM, thanks! :rocket:

**Review by kettanaito — APPROVED** [review]
Thank you for fixing this, @seriouslysean. Welcome to contributors! 🎉
