### PR TITLE
Skips "opaque" responses when handling life-cycle events

### LINKED ISSUE #529: Failed to construct 'Response': The status provided (0) is outside the range [200, 599]
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.25.0   |
| browser | Chrome     |
| OS      | macOS     |

## Request handlers

```js
// ./mocks/handlers.js

import { graphql } from 'msw'

const handlers = [
  graphql.mutation('bookAppointment', (_req, res, ctx) => res(ctx.status(422, 'Error 422 custom'))),
]

export default handlers
```

```js
// ./mocks/browser.js

import { setupWorker } from 'msw'
import handlers from './handlers'

const worker = setupWorker(...handlers)

export { worker }

```

```js
// ./index.js

if (process.env.NODE_ENV === 'development') {
    const { worker } = require('./mocks/browser')
    worker.start()
}
```
## Actual request

```js
import gql from 'graphql-tag'

export default gql`
  mutation bookAppointment($input: AppointmentRequestInput!) {
    bookAppointment(input: $input) {
        ...
      }
    }
  }
`

```

## Current behavior

When running the react application I'm getting the following logs:

```js
[MSW] Mocking enabled.

index.js:1034 Uncaught RangeError: Failed to construct 'Response': The status provided (0) is outside the range [200, 599].
    at index.js:1034
    at ServiceWorkerContainer.<anonymous> (index.js:1200)
```

Obviously the MSW is not intercepting said mutation...

Any ideas? I'm guessing that I'm making a silly mistake that I'm not able to see -_-

## Expected behavior

The only log I should see is the MSW getting initialise: 

```js
[MSW] Mocking enabled.
```

### PR DESCRIPTION
**Pull request by kettanaito**
## GitHub

- Fixes #529 

## Changes

- Response event handler now skips "opaque" responses (those originating from requests with `mode: "no-cors"`) based on their `response.type` value.
- Improves type annotation of the response object sent from the worker (it's only a partial representation of the `Response` type).

### CODE REVIEW

**Comment by kettanaito** [comment]
Hey, @timdeschryver. Thank you for writing this test. If you don't mind, I've polished it but a little. I would appreciate your review if you have a spare minute. Thanks!

**Comment by kettanaito** [comment]
I've replaced the image example with a local test server with a strict CORS policy. This produces the same exception without the fix, making the test fail. The main reason for doing so is to remove any external dependency (such as on an external image provider) in our tests. It should be possible to run all test suites offline, which implies no dependencies on actual servers. We can substitute actual servers with the `@open-draft/test-server` package.

**Comment by kettanaito** [comment]
I believe that the Codesandbox build won't succeed with this breaking change to the Service Worker file. Without the addition of the `type` property in the response sent to the client, the following like will throw indefinitely:

```
if (responseJson.type.includes('opaque')) {
```

While this isn't nice, we are going to publish this in the next minor release, indicating a breaking change. That change will imply that you have to update your worker script by `npx msw init`.

File: src/utils/worker/createResponseListener.ts [hunk 1]
```diff
@@ -12,14 +12,26 @@ export function createResponseListener(context: SetupWorkerInternalContext) {
...
+    const { payload: responseJson } = message
+
+    /**
+     * CORS requests with `mode: "no-cors"` result in "opaque" responses.
+     * That kind of responses cannot be manipulated in JavaScript due
+     * to the security considerations.
+     * @see https://fetch.spec.whatwg.org/#concept-filtered-response-opaque
+     * @see https://github.com/mswjs/msw/issues/529
+     */
+    if (responseJson.type.includes('opaque')) {
```
Comment (marcosvega91) [inline src/utils/worker/createResponseListener.ts]: I could suggest adding an extra check here. Because the `type` attribute is new, some users could not have the `service worker` updated and will receive a lot of errors. 
```suggestion
    if ("type" in responseJson && responseJson.type.includes('opaque')) {
```

**Review by marcosvega91 — CHANGES_REQUESTED** [review]
Contrary to what I have said on discord if there is a network error the service worker will not call the function `sendToClient`. I suggest only adding an extra as in the comment above, then for me is super ok :)

File: src/utils/worker/createResponseListener.ts (hunk 1 above)
Comment (kettanaito) [reply src/utils/worker/createResponseListener.ts]: Yes, this is a valid concern, but as I've mentioned [in the comment above](https://github.com/mswjs/msw/pull/564#issuecomment-766327879), this is going to be released as a breaking change. So there's no need to provide a backward-compatibility hatch.

Comment (marcosvega91) [reply src/utils/worker/createResponseListener.ts]: okok so it's ok for me 🥳

**Comment by kettanaito** [comment]
Actually, I think you're right to introduce the safety check, @marcosvega91. I've tested this once more and it produces an infinite loop with an outdated worker. I don't think that's a good experience to aim for. 

I will add a safety check that will be removed in the minor release after the next one. We'll give it 1 version to bake in.

**Review by timdeschryver — APPROVED** [review]
👍 Thanks for the cleanup!

**Review by marcosvega91 — APPROVED** [review]
Nice work 💪🏽
