### PR TITLE
fix(setupWorker): resolve the "start" promise after the worker has activated

### LINKED ISSUE #1145: "setupWorker" Promise may resolve before the worker is activated
Service Worker activation is an async process which undergoes multiple stages:

- installing
- installed
- activating
- activated

Currently, the Promise returned from `setupWorker` returns the _registration_ Promise:

https://github.com/mswjs/msw/blob/d7bdeeca6a9f0bb3f7abd6179af2babeb68e1cf7/src/setupWorker/start/createStartHandler.ts#L120

The worker registration may be in the aforementioned states when this Promise resolves. 

## Proposed behavior

The library should resolve the `setupWorker` Promise when, and only when, the worker has been registered and activated (ready to handle requests):

```ts
return workerRegistration.then((registration) => {
  const pending = registration.installing || registration.waiting
  return new Proimse((resolve) => {
    pending.addEventListener('statechange', () => {
      if (pending.state === 'activated') {
        return resolve()
      }

      // Can we assume failed activation by state alone?
    })
  })
})
```

## Context

This issue is currently failing the tests in the Karma usage example. Implementing the said fix works.

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #1145 
- May be related to #1051, #1090

### CODE REVIEW

File: src/setupWorker/start/createStartHandler.ts [hunk 1]
```diff
@@ -108,7 +104,31 @@ If this message still persists after updating, please report an issue: https://g
...
+    const workerRegistration = startWorkerInstance().then(
+      async (registration) => {
+        const pendingInstance = registration.installing || registration.waiting
+
+        // Wait until the worker is activated.
+        // Assume the worker is already activated if there's no pending registration
+        // (i.e. when reloading the page after a successful activation).
+        if (pendingInstance) {
+          await new Promise<void>((resolve) => {
+            pendingInstance.addEventListener('statechange', () => {
```
Comment (Aprillion) [inline src/setupWorker/start/createStartHandler.ts:116]: both `registration.installing.addEventListener` and `registration.waiting.addEventListener` can listen to the same event `'statechange'`?

Comment (kettanaito) [reply src/setupWorker/start/createStartHandler.ts:116]: @Aprillion yes. Those properties return a worker instance in a different state. But it's the same worker instance as the activated worker, having the same event listeners. This is how you know if a state transitions into another state.
