### PR TITLE
Consider request unhandled only when it has no handler

### LINKED ISSUE #655: getting an unhandled request error for requests that are handled but intended to be forwarded on
## Describe the bug

When using `server.listen({onUnhandledRequest: 'error'})`, I expect to see errors when there's an unhandled request, but not when the request is handled with a `return undefined`.

## Environment

- `msw: 0.27.1`
- `nodejs: 14`
- `npm: 6`

> Please also provide your browser version.

## To Reproduce

1. Clone https://github.com/kentcdodds/msw-handler-error-bug
2. Install
3. Run `node index.js`
4. See error when `mock = false` but no error when `mock = true`

## Expected behavior

There should be no error

## Screenshots

image

### PR DESCRIPTION
**Pull request by kettanaito**
## GitHub

- Fixes #655
- Closes #662

## Changes

- setupServer: Request is considered unhandled only when it has no corresponding request handler. 
- No matter what the corresponding request handler returns or not, the request is still considered handled.

### CODE REVIEW

File: src/node/createSetupServer.ts [hunk 1]
```diff
@@ -103,16 +103,16 @@ export function createSetupServer(...interceptors: Interceptor[]) {
 
         if (!handler) {
           emitter.emit('request:unhandled', mockedRequest)
-        }
-
-        if (!response) {
-          emitter.emit('request:end', mockedRequest)
 
           onUnhandledRequest(
```
Comment (kettanaito) [inline src/node/createSetupServer.ts:107]: I don't like how the worker and the server handle the same request/response flow in separate places. This opens a room to bugs, just as this one. It would be good to align this post-resolve handling into some sort of reused chain, the same for the worker and the server.

**Comment by kettanaito** [comment]
Hey, @marcosvega91 👋🏻 Would you have a minute to look at these changes? Vastly inspired by your work on #662, we are addressing the issue of that unhandled requests here.

File: src/utils/getResponse.ts [hunk 2]
```diff
@@ -44,10 +44,19 @@ export const getResponse = async <
 
     const result = await handler.run(request)
 
-    if (result === null || !result.response || result.handler.shouldSkip) {
+    if (result === null || result.handler.shouldSkip) {
       return null
     }
```
Comment (marcosvega91) [inline src/utils/getResponse.ts:49]: Hello, I don't know if it's really correct here.

I could have a handler with a `once` response that I think should be treated as handled, or not ?

**Review by marcosvega91 — CHANGES_REQUESTED** [review]
Hello @kettanaito :) It sounds good but I have one doubt

File: src/utils/getResponse.ts (hunk 2 above)
Comment (kettanaito) [reply src/utils/getResponse.ts:49]: That's a valid concern. Note that `handler.shouldSkip` checks if the handler should be skipped, not that it's a one-time handler. If you have a `res.once` running _the first time_, `result.handler.shouldSkip` will be `false`. It's only later that it will be marked as skipped:

https://github.com/mswjs/msw/blob/12bdd274c2e283bdd16448813e58b510ec676ffc/src/utils/getResponse.ts#L51-L53

On the subsequent calls that one-time handler will have `result.handler.shouldSkip` as `true`.

Comment (marcosvega91) [reply src/utils/getResponse.ts:49]: yes right, in case I have a skipped request and I don't have any other handler rather than the one skipped I will have an error of unhandled?

Comment (kettanaito) [reply src/utils/getResponse.ts:49]: @marcosvega91 exactly. After `res.once` has executed once, it's ignored until you `.resetHandlers`, so it won't be taken into account when deciding if a request is handled or not.
