### PR TITLE
Declares and exports SetupServerApi interface

### LINKED ISSUE #455: [TypeScript] missing return types of the setupServer method.
## Describe the bug
Hi!
I'm creating a mocked server as described in the guides:

```jsx
import { rest } from 'msw';
import { setupServer } from 'msw/node';

server = setupServer( ... my mocks )
```

I looked at [the code](https://github.com/mswjs/msw/blob/a446e9b1d5/src/node/createSetupServer.ts#L45), and it seems that an object is returned that contains all of the listen, use, close, etc. methods. So I understand from this that TypeScript simply does type inference when using the result of this method.

It could be great to have a type definition for this (I sometimes pass this server object to methods and don't want to use the any type).

Since I'm going to declare these types anyway in my project, I thought it would be better to just add them to this project so everybody could enjoy it.

What do you think?
Thanks 👍

### PR DESCRIPTION
**Pull request by ofekdeitch-fiverr**
## Description

Add a return type to the `setupServer` method.

### Why do we need this?
- Fixes https://github.com/mswjs/msw/issues/455

### CODE REVIEW

File: src/node/createSetupServer.ts [hunk 1]
```diff
@@ -149,7 +149,7 @@ export function createSetupServer(...interceptors: Interceptor[]) {
       /**
        * Stops requests interception by restoring all augmented modules.
        */
-      close() {
+      close(): void {
```
Comment (kettanaito) [inline src/node/createSetupServer.ts]: I believe that both argument and return types are inferred from the `ServerInstance` return type you assign to the `setupServer` function declaration. There's no need to explicitly annotate their return types as `void`.

File: src/node/glossary.ts [hunk 2]
```diff
@@ -0,0 +1,12 @@
+import { SharedOptions } from '../sharedOptions'
+import { RequestHandlersList } from '../setupWorker/glossary'
+
+export type ListenOptions = SharedOptions
```
Comment (kettanaito) [inline src/node/glossary.ts]: We can remove the `ListenOptions` type as it's effectively a copy of the `SharedOptions`. Let's use the latter directly, unless we have some extra types to union with the shared options.

```ts
listen(options?: SharedOptions): void
```

File: src/node/glossary.ts [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+
+export interface ServerInstance {
```
Comment (kettanaito) [inline src/node/glossary.ts]: Let's name this interface `SetupServerApi`, to be aligned with how a similar `setupWorker` return type is called (`SetupWorkerApi`):


https://github.com/mswjs/msw/blob/a851536cc00b23ce7c3a7d71cb5a02ae865adec0/src/setupWorker/setupWorker.ts#L8

**Review by kettanaito — CHANGES_REQUESTED** [review]
Hey, @ofekdeitch. Thank you for preparing these improvements!
I've left a few minor comments, could you please have a look at them?

File: src/node/glossary.ts (hunk 3 above)
Comment (marcosvega91) [reply src/node/glossary.ts]: we can move then `SetupWorkerApi` in his glossary file? In this way we have the same structure

Comment (kettanaito) [reply src/node/glossary.ts]: That's a sound suggestion, @marcosvega91!

**Comment by ofekdeitch-fiverr** [comment]
Hey guys ( @kettanaito  @marcosvega91 ),
Fixed the comments 👍 

Please notice that I also moved the comments from the implementation of `SetupServerApi` to its definition in the glossary file (the same has been done before with `SetupWorkerApi`).

**Comment by ofekdeitch-fiverr** [comment]
One last comment - I guess I should also bump the patch\minor version - whatever you guys prefer.

**Comment by kettanaito** [comment]
@ofekdeitch-fiverr, thank you for addressing the comments!
No need to bump the version, that will be done by one of the library's maintainers once your improvement lands.

**Comment by kettanaito** [comment]
I've rebased the feature branch and added an additional commit that drops the inferred argument types from the `setupWorker` return object. Let's wait for the CI.

File: src/node/glossary.ts [hunk 4]
```diff
@@ -0,0 +1,29 @@
+import { SharedOptions } from '../sharedOptions'
+import { RequestHandlersList } from '../setupWorker/glossary'
+
+export interface SetupServerApi {
```
Comment (marcosvega91) [inline src/node/glossary.ts:4]: To make the interface accessibile we should export from `node/index.ts`

File: src/setupWorker/glossary.ts [hunk 5]
```diff
@@ -76,3 +78,22 @@ export type ResponseWithSerializedHeaders<BodyType = any> = Omit<
 > & {
   headers: HeadersList
 }
+export interface SetupWorkerApi {
```
Comment (marcosvega91) [inline src/setupWorker/glossary.ts:82]: Same as `setup-worker` but from `index.ts`

File: test/msw-api/setup-worker/resetHandlers.test.ts [hunk 6]
```diff
@@ -1,7 +1,7 @@
 import * as path from 'path'
 import { rest } from 'msw'
 import { runBrowserWith } from '../../support/runBrowserWith'
-import { SetupWorkerApi } from '../../../src/setupWorker/setupWorker'
+import { SetupWorkerApi } from '../../../src/setupWorker/glossary'
```
Comment (marcosvega91) [inline test/msw-api/setup-worker/resetHandlers.test.ts]:
```suggestion
import { rest, SetupWorkerApi } from 'msw'
```

File: test/msw-api/setup-worker/restoreHandlers.test.ts [hunk 7]
```diff
@@ -1,7 +1,7 @@
 import * as path from 'path'
 import { rest } from 'msw'
 import { runBrowserWith } from '../../support/runBrowserWith'
-import { SetupWorkerApi } from '../../../src/setupWorker/setupWorker'
+import { SetupWorkerApi } from '../../../src/setupWorker/glossary'
```
Comment (marcosvega91) [inline test/msw-api/setup-worker/restoreHandlers.test.ts]:
```suggestion
import { rest, SetupWorkerApi } from 'msw'
```

File: test/msw-api/setup-worker/use.test.ts [hunk 8]
```diff
@@ -1,7 +1,7 @@
 import * as path from 'path'
 import { rest } from 'msw'
 import { runBrowserWith } from '../../support/runBrowserWith'
-import { SetupWorkerApi } from '../../../src/setupWorker/setupWorker'
+import { SetupWorkerApi } from '../../../src/setupWorker/glossary'
```
Comment (marcosvega91) [inline test/msw-api/setup-worker/use.test.ts]:
```suggestion
import { rest, SetupWorkerApi } from 'msw'
```

**Review by marcosvega91 — CHANGES_REQUESTED** [review]
We should export the new interfaces to make them accessibile from the library ?

File: src/node/glossary.ts (hunk 4 above)
Comment (kettanaito) [reply src/node/glossary.ts:4]: Thank you for the suggestion. Addressed.

**Comment by kettanaito** [comment]
Hey, @ofekdeitch-fiverr. I've rebased the branch against the latest `master` and provided some of the suggestions Marco has mentioned above. I hope it's okay.

**Review by kettanaito — DISMISSED** [review]

**Comment by kettanaito** [comment]
I trust we can merge this once the CI is green.
