### PR TITLE
fix(react-native): import "node:events" lazily

### LINKED ISSUE #1847: Expo / React Native not having support for 'events'
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

21.1.0

### Reproduction repository

https://github.com/Cocolis-1/blank-expo/tree/feat/msw

### Reproduction steps

Try to start the bundler using yarn start and start your dev client.

### Current behavior

You should see the following error:
```
iOS Bundling failed
The package at "node_modules/msw/lib/native/index.js" attempted to import the Node standard library module "events".
It failed because the native React runtime does not include the Node standard library.
Learn more: https://docs.expo.dev/workflow/using-libraries/#using-third-party-libraries
```

### Expected behavior

MSW should not depend on node:events (if possible) so that React Native users can use it.
I think the commit introducing node:events is [this one](https://github.com/mswjs/msw/commit/1033f651291f67a0ce509af965fdd0aa50fa7509).
Let me know if I can help in any way!

Thanks!

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #1847 

## Changes

- Adds a `context` on the `SetupServerApi` class. 
- Adds `context.nodeEvents()` getter that lazily imports `node:events` and returns `undefined` if the import failed (e.g. in React Native). 
- Moves the `AbortSignal` max listeners handling from the request listener to a private method of the `SetupServerApi` class. Makes it fail-fast.

### CODE REVIEW

File: src/node/SetupServerApi.ts [hunk 1]
```diff
@@ -47,48 +48,22 @@ export class SetupServerApi
     this.init()
   }
 
+  private createContext(): SetupServerInternalContext {
+    return {
+      get nodeEvents() {
+        return import('node:events')
```
Comment (kettanaito) [inline src/node/SetupServerApi.ts:54]: I _think_ this Promise should only ever fire once. I'm not sure if I'm structuring this correctly but the intention is to try to import this module _once_ so each outgoing request (request listener) doesn't pend on this import, increasing the response time).

**Review by mattcosta7 — APPROVED** [review]
I think this makes sense, hopefully that helps work around the issues with this api in react-native like environments. 

Re the import promise only being called once, I think it should resolve immediately since `import` calls are cached as far as I know, so that should be fine

**Comment by DogukanTansuk** [comment]
@mattcosta7 Can we release a beta version with this change? I could try and give feedback.

**Comment by kettanaito** [comment]
@DogukanTansuk, you can always install a package from a particular branch/commit. I believe all modern package managers support that (NPM, Yarn, PNPM). You can install it that way and let me know if this fixes the issue? Thanks!

**Comment by kettanaito** [comment]
I'm promoting this to a release candidate because the change is backward-compatible and has no effect on the existing `msw/node` integrations. Folks would have to give this a try for `msw/native` and report back whether the issue is fixed. That's the optimal course of action until we have an official React Native example we can run in the existing smoke tests pipeline.

**Comment by kettanaito** [comment]
## Released: v2.0.7 🎉

This has been released in v2.0.7!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.0.7)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.0.7)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
