### PR TITLE
fix: clone Response before logging

### LINKED ISSUE #1640: Consistent "TypeError: Failed to execute 'text' on 'Response': body stream already read" since v1.2.2
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/JKapitein/msw-bodystream

### Reproduction steps

`yarn cypress-serve`
Can reach it locally from this point if you want, or
`yarn cypress-run`

### Current behavior

Failed to execute 'text' on 'Response': body stream already read

```
// src/utils/logging/serializeResponse.ts
var import_headers_polyfill9 = require("headers-polyfill");
async function serializeResponse(response2) {
  return {
    status: response2.status,
    statusText: response2.statusText,
    headers: (0, import_headers_polyfill9.flattenHeadersObject)((0, import_headers_polyfill9.headersToObject)(response2.headers)),
    body: await response2.text()
  };
}
```

### Expected behavior

The request completes without throwing an error as in 1.2.1

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #1640

## Changes

- The `IsomorphicResponse -> Response` construction for the fallback mode (in-browser only) now uses the standard `Response` class (every response can now be cloned).
- Clone the response in the `serializeResponse` before reading its body.
- Also clone the response _immediately_ on the regular worker response handling.

### CODE REVIEW

File: src/utils/request/createResponseFromIsomorphicResponse.ts [hunk 1]
```diff
@@ -1,34 +1,11 @@
...
 
 export function createResponseFromIsomorphicResponse(
   response: IsomorphicResponse,
 ): Response {
-  return {
-    ...response,
-    ok: response.status >= 200 && response.status < 300,
-    url: '',
-    type: 'default',
+  return new Response(response.body, {
```
Comment (kettanaito) [inline src/utils/request/createResponseFromIsomorphicResponse.ts:6]: It scares me a bit why the previous logic was contrived here. This function is only called in the fallback mode, which is browser-only if the Service Worker API is not available (old browsers, locally-served apps). Since we are in the browser, we can rely on `Response`, we always could.

**Review by wjkawecki — APPROVED** [review]

**Comment by kettanaito** [comment]
## Released: v1.2.3 🎉

This has been released in v1.2.3!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v1.2.3)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/1.2.3)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
