### PR TITLE
fix: transfer mocked response as ArrayBuffer to the worker

### LINKED ISSUE #1324: MSW fails to resolve response on Safari
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Safari

### Reproduction repository

https://github.com/netcoding87/msw-safari

### Reproduction steps

- `npm install`
- `npm run start`
- Open console in browser
- Click button "Fetch some data"
=> 'click' and the response object are logged, but not the result from `response.json()`

### Current behavior

The response object does not resolve the data in Safari. In other browsers (chromium, firefox) it is working... 

### Expected behavior

The response object resolves the data and the app can work with the responded data in Safari browsers

### LINKED ISSUE #1325: The response is intermittently not returned in the Firefox.
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Firefox

### Reproduction repository

I've tried to create example in codesandbox, but i've got error ([MSW] Failed to execute `setupWorker` in a non-browser environment. Consider using `setupServer` for Node.js environment instead.)

### Reproduction steps

1. Create mock
2. Try to get data from this mock in Firefox (v102, MacOS version)
3. U will get smth like this:
Снимок экрана 2022-07-13 в 15 37 27

### Current behavior

Response doesn't end
In Chrome everything alright, this behaviour appeared in `msw@0.43`

### Expected behavior

The response must be ended

### PR DESCRIPTION
**Pull request by kettanaito**
## GitHub

- Fixes #1324 
- Fixes #1325

## Changes

- **Removes the streaming of mocked responses from the client to the worker**. I've come to realize this internal change introduced more problems than issues it solved. We should design proper stream support in #1336, and we may need to wait for all browsers to support sending `ReadableStream` as a `transfer` object on `postMessage()`. 
- Refactors the worker message channel to support `transport` in `postMessage()`.
- Sends mocked response body as `ArrayBuffer` to the worker.
- Removes `INTERNAL_ERROR` worker event. Internal (request handler) errors are handled in the library now, and the library sends a regular mocked response to the worker in their case. 
- Changes the shape of the object transferred from the client to the worker.

## Roadmap

- [x] Ensure this change doesn't introduce a regression of #581

### CODE REVIEW

**Comment by kettanaito** [comment]
This change can't introduce a regression because `ReadableStream` as a mocked response body is not yet supported.

**Comment by kettanaito** [comment]
Hi, @95th 👋 Please, would you have a minute to review these changes? Thank you.

File: src/setupWorker/start/utils/createMessageChannel.ts [hunk 1]
```diff
@@ -11,36 +11,20 @@ export interface ServiceWorkerMessage<
...
-      ? { type: Event }
-      : {
-          type: Event
-          payload: Parameters<ServiceWorkerFetchEventMap[Event]>[0]
-        },
-  ): void
+interface WorkerChannelEventsMap {
+  MOCK_RESPONSE: (data: SerializedResponse<any>, body?: [ArrayBuffer]) => void
+  NOT_FOUND: () => void
+  NETWORK_ERROR: (data: { name: string; message: string }) => void
```
Comment (95th) [inline src/setupWorker/start/utils/createMessageChannel.ts]: I think we can simplify the types to represent only the body and have transfer optionally present.

like so:
```ts
interface WorkerChannelEventsMap {
  MOCK_RESPONSE: SerializedResponse<any>
  NOT_FOUND: void
  NETWORK_ERROR: { name: string; message: string }
}
```

and use it with WorkerChannel like:

```ts
  public postMessage<Event extends keyof WorkerChannelEventsMap>(
    event: Event,
    data: WorkerChannelEventsMap[Event],
    transfer?: [ArrayBuffer]
  ): void {
    this.port.postMessage({ type: event, data }, { transfer })
  }
```

Comment (kettanaito) [reply src/setupWorker/start/utils/createMessageChannel.ts]: That's a great idea! We gain no benefit of keeping events map values as functions, as the return type is disregarded. Will adjust this.

Comment (kettanaito) [reply src/setupWorker/start/utils/createMessageChannel.ts]: Done!

**Comment by kettanaito** [comment]
## Released: v0.44.2 🎉

This has been released in v0.44.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v0.44.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/0.44.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
