### PR TITLE
Fixes invariant predicate for "init" command

### LINKED ISSUE #132: CLI: msw init prompt information error
## msw init prompt information error
```
$ npx msw init ./public

Initializing the Mock Service Worker at '......'
Failed to copy Service Worker. null
```
msw is executed successfully, the file is copied normally, but the failure message is prompted

## Environment

- `"msw": "^0.15.3"`

## fix
cli/init.js
```js
fs.copyFile(SERVICE_WORKER_BUILD_PATH, swDestFilepath, (error) => {
 invariant(typeof error === null, 'Failed to copy Service Worker. %s', error)

 ...
}
```
`error` If there is no error message, it is `null`
`typeof null => 'object'`

fix
```js
fs.copyFile(SERVICE_WORKER_BUILD_PATH, swDestFilepath, (error) => {
 invariant(error === null, 'Failed to copy Service Worker. %s', error)

 ...
}
```
or
```js
fs.copyFile(SERVICE_WORKER_BUILD_PATH, swDestFilepath, (error) => {
 invariant(!error, 'Failed to copy Service Worker. %s', error)

 ...
}
```

### PR DESCRIPTION
**Pull request by kettanaito**
## Changes

According to how `invariant()` is generally used, as long as its predicate is truthy, it must not throw. This means that its predicate must describe a _desired_ behavior, not an exceptional one.

## GitHub

- Fixes #132

### CODE REVIEW

**Review by hehehai — APPROVED** [review]

File: cli/init.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ module.exports = function init(args) {
   const swDestFilepath = path.resolve(resolvedPublicDir, swFilename)
 
   fs.copyFile(SERVICE_WORKER_BUILD_PATH, swDestFilepath, (error) => {
-    invariant(typeof error === null, 'Failed to copy Service Worker. %s', error)
+    invariant(error == null, 'Failed to copy Service Worker. %s', error)
```
Comment (kettanaito) [inline cli/init.js:29]: We are expecting that `error` will not exist:

```
undefined == null // true
null == null // true
new Error == null // false, will throw
```

**Comment by kettanaito** [comment]
Thanks for the review, @hehehai! 
Re-running the CI remotely, passes on local.
