### PR TITLE
fix(HttpResponse): support non-configurable status codes

### LINKED ISSUE #2433: RangeError: init["status"] must be in the range of 200 to 599, inclusive.
### Prerequisites

- [x] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [x] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [x] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [x] I'm using Node.js version 18 or higher

### Node.js version

v22

### Reproduction repository

—

### Reproduction steps

```ts
expect(new HttpResponse(null, { status: 101 })).toHaveProperty('status', 101)
```

### Current behavior

```
 FAIL  src/core/HttpResponse.test.ts > supports non-configurable status codes
RangeError: init["status"] must be in the range of 200 to 599, inclusive.
 ❯ new HttpResponse src/core/HttpResponse.ts:41:5
     39|   constructor(body?: BodyInit | null, init?: HttpResponseInit) {
     40|     const responseInit = normalizeResponseInit(init)
     41|     super(body, responseInit)
       |     ^
     42|     decorateResponse(this, responseInit)
     43|   }
```

### Expected behavior

I am able to construct a mocked response instance with a non-configurable status code. 

This is supported on the Interceptors' side. MSW seems to be behind.

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #2433 

With this fix, you will be able to do this:

```ts
new HttpResponse(null, { status: 101 })
```

> No direct changes necessary in MSW. We should rely on `FetchResponse` from Interceptors, to begin with. It bakes in a bunch of useful, uncommon behaviors that are expected in the context of mocking.

### CODE REVIEW

File: src/core/HttpResponse.ts [hunk 1]
```diff
@@ -1,3 +1,4 @@
+import { FetchResponse } from '@mswjs/interceptors'
```
Comment (kettanaito) [inline src/core/HttpResponse.ts:1]: `FetchResponse` extends the global `Response` so it's safe to use both in Node.js and in the browser. I hope the root export of Interceptors doesn't load anything Node.js-specific (it mustn't).

File: src/core/HttpResponse.ts [hunk 2]
```diff
@@ -167,7 +168,7 @@ export class HttpResponse extends Response {
       responseInit.headers.set('Content-Length', body.byteLength.toString())
     }
 
-    return new HttpResponse(body, responseInit)
+    return new HttpResponse(body as ArrayBuffer, responseInit)
```
Comment (kettanaito) [inline src/core/HttpResponse.ts:171]: Most likely a Node.js typings hiccup.

**Comment by kettanaito** [comment]
## Released: v2.7.1 🎉

This has been released in v2.7.1!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.7.1)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.7.1)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
