### PR TITLE
fix(setupWorker): emit the correct life-cycle events for bypassed requests

### LINKED ISSUE #2053: Browser: Cannot read properties of undefined (reading 'url')
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/hal-shin/msw-bug

### Reproduction steps

Run `yarn install`
Run `yarn start`

If server starts normally, kill the server and run `yarn start` again. Within ~5 server restarts, you run into the error.

It looks like the following line (line 21, createResponseListener.ts) is the problem:

`const request = context.requests.get(requestId)!`

Whereby `request` is undefined.

### Current behavior

`caught TypeError: Cannot read properties of undefined (reading 'url')
    at createResponseListener.ts:58:1
    at ServiceWorkerContainer.<anonymous> (setupWorker.ts:84:1)`

image

### Expected behavior

Server to start without errors or crashing every time.

### LINKED ISSUE #2083: Cannot read properties of undefined (reading 'url')
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

N/A

### Reproduction steps

msw version: 2.2.1

For some reason, the `request` object [here](https://github.com/mswjs/msw/blob/main/src/browser/setupWorker/start/createResponseListener.ts#L21) is occasionally undefined. When it is, [this line ](https://github.com/mswjs/msw/blob/main/src/browser/setupWorker/start/createResponseListener.ts#L58) throws

```
Cannot read properties of undefined (reading 'url')
```

Seem to be introduced during https://github.com/mswjs/msw/commit/0e9d65ffbfb1f83a47c7dc2fcb2c885cbbf5d2ac

I don't know if this is intentional or not, or what the fix is, just reporting this runtime error.  Thanks for all you do!

### Current behavior

Throws

```
Cannot read properties of undefined (reading 'url')
```

### Expected behavior

Does not throw this error

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #2053
- Fixes #2083
- Closes #2054
- Depends on #2093

### CODE REVIEW

**Comment by kettanaito** [comment]
Added a failing test for the bypass scenario. Also added a missing test for the passthrough scenario (that one is passing).

File: src/mockServiceWorker.js [hunk 1]
```diff
@@ -206,13 +206,6 @@ async function getResponse(event, client, requestId) {
     return passthrough()
   }
 
-  // Bypass requests with the explicit bypass header.
-  // Such requests can be issued by "ctx.fetch()".
-  const mswIntention = request.headers.get('x-msw-intention')
```
Comment (kettanaito) [inline src/mockServiceWorker.js:211]: Both bypassed and passthrough requests _must_ emit the `REQUEST` event to the client so the client (worker context) stores that request in memory. Then, it can find the request instance based on the `requestId` when receiving the `RESPONSE` event, which right now both mocked and bypassed responses do send correctly.

**Comment by kettanaito** [comment]
## Released: v2.2.6 🎉

This has been released in v2.2.6!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.2.6)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.2.6)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by dalhaan** [comment]
Hey @kettanaito,

Did you mean to leave the following line:
`console.log('RESPONSE LISTENER', responseJson, context.requests)`

in `src/browser/setupWorker/start/createResponseListener.ts`?

After upgrading, the logs seem to be spamming the console and I can't seem to be able to disable them.

**Comment by piotr-cz** [comment]
There is an issue https://github.com/mswjs/msw/issues/2098 for added `console.log` line

**Comment by kettanaito** [comment]
@piotr-cz, thanks! Fixed in #2099.
