### PR TITLE
fix: implement cookie persistence using `tough-cookie`

### LINKED ISSUE #2181: Cookie with path other than root not sent to handlers
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://codesandbox.io/p/sandbox/cocky-torvalds-nsmhv6

### Reproduction steps

Just visit the CodeSandbox and see how `goodCookie` is visible, but `badCookie` is not.

### Current behavior

Cookies with paths other than `/` are not being sent.

If you set two cookies as follows:

```js
      return HttpResponse.text("COOKIES SET", {
        headers: [
          [
            "Set-Cookie",
            "goodCookie=goodCookie; Path=/; SameSite=None; Secure; Max-Age=20;",
          ],
          [
            "Set-Cookie",
            "badCookie=badCookie; Path=/some/path; SameSite=None; Secure; Max-Age=20;",
          ],
        ],
      });
```

When making api calls to correctly matching paths, `goodCookie` is sent properly, but `badCookie` is not.

- Both cookies are correctly set in the browser. It is an issue during requests.
- I can confirm that the issue is not present if using `@mswjs/http-middleware`.
- **It works if you go to `/some/path` (`https://nsmhv6.csb.app/some/path`) in the CodeSandbox. Probably MSW is using the browser's URL and not the request URL to match cookies to send?**

### Expected behavior

I expect cookies to behave according to the specified path upon creation.

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #2181 
- Fixes the issue where `HttpOnly` cookies are not exposed to the `cookies` argument of the response resolver.

This is a rework of the request/response cookie handling. Since v2, I believe the previous logic has become obsolete. We are forwarding the mocked response cookies to the `document.cookie` but we won't be able to read them back if those cookies are not exposed to JavaScript (like `HttpOnly` cookies). Neither would we be able to read them back from the `response.headers.get('set-cookie')` because that's a forbidden header field. 

In this rework, I'm removing `@mswjs/cookies` and introducing [`tough-cookie`](https://github.com/salesforce/tough-cookie) and its `CookieJar` class to get cookie filtering and, eventually, persistence (has to be implemented separately through a custom `Store`). 

## Roadmap

- [x] Improve test coverage of cookie-related scenarios. This includes request and response cookies. (some work already done in https://github.com/mswjs/msw/tree/fix/wip-cookie-path-match)
- [x] Fix the `require` leaking through `tough-cookie` (is it CJS-only?)
  - Fixed by using [`@bundled-es-modules/tough-cookie`](https://github.com/bundled-es-modules/tough-cookie)
- [x] **Implement persistence** (will be evident once we add tests). Store the cookies in `localStorage` so they persist across page refreshes.

### CODE REVIEW

File: src/core/utils/request/getRequestCookies.ts [hunk 1]
```diff
@@ -1,75 +1,19 @@
...
-  /**
-   * @todo Consider making this a separate step so this function
-   * is pure-er.
-   */
-  for (const [name, value] of Object.entries(forwardedCookies)) {
-    request.headers.append('cookie', cookieUtils.serialize(name, value))
-  }
+  const cookiesFromStore = Object.fromEntries(
+    cookieStore
+      .getCookiesSync(request.url)
```
Comment (kettanaito) [inline src/core/utils/request/getRequestCookies.ts]: The `tough-cookie` package implements specification-compliant way of returning matching cookies for the given URL. It's maintained and well-used. I see no reason for us to rely on `@mswjs/cookies` anymore.

File: src/core/utils/HttpResponse/decorators.ts [hunk 2]
```diff
@@ -38,21 +40,35 @@ export function decorateResponse(
...
-      // as the valid cookie string to begin with.
-      document.cookie = cookieString
+  const responseCookies = init.headers.get('set-cookie')
+
+  if (responseCookies) {
+    // Record the raw "Set-Cookie" response header provided
+    // in the HeadersInit. This is later used to store these cookies
+    // in cookie jar and return the right cookies in the "cookies"
+    // response resolver argument.
+    Object.defineProperty(response, kSetCookie, {
```
Comment (kettanaito) [inline src/core/utils/HttpResponse/decorators.ts:50]: I would love to store the cookies here directly but `tough-cookie` needs a URL to associate the cookies with. `response.url` is not always defined (this may be easier to solve). I don't like introducing a symbol just to pass the data around.

**Comment by kettanaito** [comment]
## Released: v2.3.3 🎉

This has been released in v2.3.3!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.3.3)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.3.3)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
