### PR TITLE
onUnhandledRequest: Suppress exceptions when parsing potential GraphQL requests

### LINKED ISSUE #732: REST query is mistaken for GraphQL query and can't be intercepted (throws an error)
## Environment

| Name    | Version |
| ------- | ------- |
| msw     | 0.28.2   |
| browser | Chrome     |
| OS      | Mac OS X Catalina    |

## Request handlers

no request handler for the following rest request 

```js
https://api.dev/artists?query=Petit+Biscuit&page=0&limit=5&workspaceId=ce54f030-2191-40b1-8b2a-cd5167e9ec5f
```

## Actual request

```js
const results = await Axios.get('/artists', {
    params: {
      query,
      page,
      limit,
      workspaceId,
      onlyBelieveArtists,
    },
  });
```

## Current behavior

Browser console throws an error : 

> [MSW] Failed to intercept a GraphQL request to "GET https://api.dev/artists": cannot parse query. See the error message from the parser below.

## Expected behavior

no error shoud be thrown as it is not a GraphQL request

this happens in 

`parseGraphQLRequest` method

seemingly because it relies on the presence of a _query_ param to start and parse the query

should this method even be called? maybe it should as no rest handler is provided it also tries to find a graphQL handler

thanks for any input on this

### PR DESCRIPTION
**Pull request by thomasmery**
- Fixes https://github.com/mswjs/msw/issues/732

Tries and apply what @kettanaito suggested to avoid logging an error when an unhandled rest request containing a _query_ param would result in a confusing error message in the console

@kettanaito  please let me know if this is what you meant and/or how this can be improved

thanks

### CODE REVIEW

File: src/utils/request/onUnhandledRequest.ts [hunk 1]
```diff
@@ -116,6 +116,17 @@ ${handlers.map((handler) => `  • ${handler.info.header}`).join('\n')}`
   return `Did you mean to request "${handlers[0].info.header}" instead?`
 }
 
+export function tryAndSilenceIfThrows<Payload>(
```
Comment (kettanaito) [inline src/utils/request/onUnhandledRequest.ts]: What do you think about:

```ts
export function withoutExceptions
```

Comment (kettanaito) [inline src/utils/request/onUnhandledRequest.ts]: Could you please move this utility function to `src/utils/internal`? That's the directory where we keep such internal helpers.

File: src/utils/request/onUnhandledRequest.ts [hunk 2]
```diff
@@ -126,7 +137,10 @@ export function onUnhandledRequest(
     return
   }
 
-  const parsedGraphQLQuery = parseGraphQLRequest(request)
+  // TODO: comment and exlain why we don't want to ignore the error if parsing fails here
```
Comment (kettanaito) [inline src/utils/request/onUnhandledRequest.ts]: We actually _want_ to ignore any errors originating during this parsing. I'll provide some explanation below.

```ts
/**
 * @note Ignore any parsing exceptions.
 * At this step, the library cannot guarantee that the unhandled request
 * is a valid GraphQL requests. Since the point of this function is to
 * provide smart suggestions and not ensure a request's type validity,
 * the exception during GraphQL parsing only means that this request
 * is not a valid GraphQL request and shouldn't be suggested as such.
 */
```

File: src/utils/internal/parseGraphQLRequest.ts [hunk 3]
```diff
@@ -157,11 +157,9 @@ export function parseGraphQLRequest(
 
     // Encountered a matching GraphQL request that is syntactically invalid.
     // We may consider getting the parsing error and propagating it to the user.
-    console.error(
+    throw new Error(
```
Comment (kettanaito) [inline src/utils/internal/parseGraphQLRequest.ts:158]: Could you please adjust the tests for `src/utils/internal/parseGraphQLRequest.test.ts` to reflect this change?

File: src/utils/request/onUnhandledRequest.ts (hunk 1 above)
Comment (kettanaito) [inline src/utils/request/onUnhandledRequest.ts]: Please, would you be comfortable writing a few unit tests for this helper function? 
Let me know if you need any help, I'd be glad to help you with the tests.

**Review by kettanaito — CHANGES_REQUESTED** [review]
Thank you for working on these improvements, @thomasmery!
They look great. I've left a few comments, could you please let me know what you think about them?

Looking forward to seeing this fix merged.

**Comment by thomasmery** [comment]
@kettanaito will get to it as soon as I am able :)

thanks for the guidance!

**Comment by kettanaito** [comment]
Hey, @thomasmery. I've updated your feature branch against the latest state of the repo and polished the implementation a little, mainly adding missing tests. I hope you don't mind. Looks good to get it merged, waiting for the CI to pass.

**Review by kettanaito — DISMISSED** [review]

File: src/handlers/GraphQLHandler.ts [hunk 4]
```diff
@@ -108,7 +109,10 @@ export class GraphQLHandler<
   }
 
   parse(request: MockedRequest) {
-    return parseGraphQLRequest(request)
+    return tryCatch(
+      () => parseGraphQLRequest(request),
+      (error) => console.error(error.message),
```
Comment (kettanaito) [inline src/handlers/GraphQLHandler.ts:114]: Handling parsing exceptions as console errors to preserve the previous behavior. At the moment, when parsing a request in a _graphql handler_ fails, it doesn't produce a 500 response, but a console error including the parsing error.

**Review by kettanaito — APPROVED** [review]

**Comment by thomasmery** [comment]
@kettanaito ah so sorry - it was just not possible to follow up - thanks for your kindness and this great project
