### PR TITLE
fix: transfer response buffer on safari

### LINKED ISSUE #1757: DataCloneError: The object cannot be cloned in Safari v17 (using fetch-based MSW)
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Safari

### Reproduction repository

https://github.com/thepassle/msw-safari-repro

### Reproduction steps

- `npm i`
- `npm start`
- open browser in safari 17

### Current behavior

repro

### Expected behavior

No error and the object is cloned successfully

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #1757
- Related to #1436 
- Originally reported [here](https://github.com/mswjs/msw/pull/1436#issuecomment-1762701825)

## Motivation

Fixes an issue where sending a `ReadableStream` via `messageChannel.port1.postMessage()` throws the following error on Safari:

```
DataCloneError: The object can not be cloned.
```

## Solution

MSW will run a quick supports check for `ReadableStream` as transferable. If it fails, MSW will read the mocked response's `ArrayBuffer` body and send it _at once_ to the worker. This still means that mocking streams won't work in Safari as reading the response body will exhaust its stream so it loses the chunks/timings information when the client will receive it. 

That's acceptable since it's an issue in Safari and must be addressed there.

### CODE REVIEW

File: src/browser/setupWorker/start/createRequestListener.ts [hunk 1]
```diff
@@ -47,18 +48,29 @@ export const createRequestListener = (
...
-            const responseStream = responseClone.body
 
-            messageChannel.postMessage(
-              'MOCK_RESPONSE',
-              {
+            /**
+             * @note Safari doesn't support transferring a "ReadableStream".
+             * Check that the browser supports that before sending it to the worker.
+             */
+            if (supportsReadableStreamTransfer()) {
```
Comment (kettanaito) [inline src/browser/setupWorker/start/createRequestListener.ts]: I dislike checking this on _every_ response listener. 

This should be determined _once_ because its value is bound to the current browser and cannot change on runtime. 

We should move this somewhere to the `setupWorker()` call, I think. It's computed once, even before handling the first response, and stored in the worker context. Something like `worker.context.supportsReadableStreamTransfer` can work.

File: src/browser/setupWorker/start/createRequestListener.ts [hunk 2]
```diff
@@ -47,18 +48,29 @@ export const createRequestListener = (
...
+                'MOCK_RESPONSE',
+                {
+                  ...responseInit,
+                  body: responseStream,
+                },
+                responseStream ? [responseStream] : undefined,
+              )
+            } else {
+              // As a fallback, send the response body buffer to the worker.
+              const responseBuffer = await responseClone.arrayBuffer()
```
Comment (kettanaito) [inline src/browser/setupWorker/start/createRequestListener.ts:67]: @thepassle, would this work for your use case if we read the mocked response body as `ArrayBuffer` instead of `Blob`? I find it to be more correct.

File: src/browser/setupWorker/setupWorker.ts [hunk 3]
```diff
@@ -142,8 +143,11 @@ export class SetupWorkerApi
           })
         },
       },
-      useFallbackMode:
-        !('serviceWorker' in navigator) || location.protocol === 'file:',
+      supports: {
+        serviceWorkerApi:
```
Comment (kettanaito) [inline src/browser/setupWorker/setupWorker.ts:147]: This is a good chance to move `useFallbackMode` to `supports.serviceWorkerApi` since now we check for two things on the side of browser's support.

File: src/browser/setupWorker/start/createRequestListener.ts (hunk 2 above)
Comment (thepassle) [reply src/browser/setupWorker/start/createRequestListener.ts:67]: looks like it works: 
image

**Comment by thepassle** [comment]
tried this out locally and it seems to work, lgtm

File: src/browser/setupWorker/start/createRequestListener.ts (hunk 2 above)
Comment (kettanaito) [reply src/browser/setupWorker/start/createRequestListener.ts:67]: Awesome! 

In the future, we should print a warning if the developer is mocking a `ReadableStream` body while transferring that stream isn't supported by their browser. We will still use the fallback to `ArrayBuffer` but the developer may be confused lest we show a warning of what's happening.
