### PR TITLE
Warns on the redundant usage of query parameters

### LINKED ISSUE #231: There is no warning when using query params in the handler URL
## Describe the bug
The following mock will never work since the query strings are removed from the original URL but not from the handler URL:

```js
rest.get("/foo?bar=10", (req, res, ctx) => {
  return res(
    ctx.json({
      foo: "bar",
    })
  );
}),
```

## Environment

- `msw: 0.19.0`
- `nodejs: 12.17.0`
- `npm: 6.14.4`

## To Reproduce
1. Add the handler mentioned above
2. In the app, do a request to `/foo?bar=10`
3. Error: the request is not mocked

## Expected behavior
There should be an warning explaining why the mock won't work and how to fix the problem

### PR DESCRIPTION
**Pull request by kettanaito**
## Changes

- Resolves a `rest.*` mask to a `URL` instance, if possible. That instance is later used for both request matching in predicate and retrieving URL query params to produce a meaningful warning message on redundant query parameters.

## GitHub

- Fixes #231

### CODE REVIEW

**Review by marcosvega91 — APPROVED** [review]
awesome work 🥳

File: src/rest.ts [hunk 1]
```diff
@@ -51,12 +52,20 @@ const createRestHandler = (method: RESTMethods) => {
...
+        ? resolvedMask
+        : resolveRelativeUrl(resolvedMask)
+
     return {
       predicate(req) {
         // Ignore query parameters and hash when matching requests URI
         const cleanUrl = getCleanUrl(req.url)
         const hasSameMethod = isStringEqual(method, req.method)
-        const urlMatch = match(resolveRelativeUrl(mask), cleanUrl)
+        const urlMatch = match(cleanMask, cleanUrl)
```
Comment (kettanaito) [inline src/rest.ts:68]: I don't think it's necessary to pass a `cleanMask` here. It should be possible to revert back to `resolveRelativeUrl(mask)` usage, which would make `cleanMask` not needed (?).

Comment (marcosvega91) [reply src/rest.ts:68]: without the use of `cleanMask` I think that match will fail, because you'll compare the mask, with query parameters, and the cleanUrl

Comment (kettanaito) [reply src/rest.ts:68]: Nice catch! Thanks for highlighting that, I suppose I've overlooked that :)

**Comment by kettanaito** [comment]
Thank you for the review, @marcosvega91!

Once more sorry for turning down the original pull request. Hey, if you're still interested in contributing to MSW, I can suggest #217, #218, #227, #228. There are quite a few issues I haven't got to yet, I'd appreciate a help. Thanks.

File: src/rest.ts (hunk 1 above)
Comment (marcosvega91) [reply src/rest.ts:68]: It's good to contribute in someway :)

**Comment by marcosvega91** [comment]
I'll take a look to one of them 🦹
